version: 0.2

phases:
  pre_build:
    commands:
      - echo Instalando dependencias do PHP
      - composer install
      
  build:
    commands:
      - vendor/bin/phpunit

  post_build:
    commands:
      - php artisan migrate --force
      
artifacts:
  files:
    - '**/*'
